service: test-serverless-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: get

  rest_mocked_posts:
    handler: handler.rest_mocked_posts
    events:
     - http:
         path: mocked_posts
         method: get
         cors: true

  rest_pg_posts:
    handler: handler.rest_pg_posts
    events:
     - http:
         path: posts
         method: get
         cors: true
